#!/usr/bin/python3
def factorize(n):
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return (i, n // i)
    return (n, 1)

numbers = [4, 12, 34, 128, 1024, 4958, 1718944270642558716715, 9, 99, 999, 9999, 9797973, 49, 239809320265259]

for n in numbers:
    p, q = factorize(n)
    print(f"{n}={p}*{q}")
