#!/usr/bin/python3
def small_prime_factors(n):
    """Iterate over the small prime factors of a number."""
    prime_factors = []
    while n % 2 == 0:
        prime_factors.append(2)
        n = n // 2
    for i in range(3, int(n ** 0.5) + 1, 2):
        while n % i == 0:
            prime_factors.append(i)
            n = n // i
    if n > 2:
        prime_factors.append(n)
    return prime_factors

n = 100
for factor in small_prime_factors(n):
    print(factor)
